FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update
RUN apt-get -y install curl
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get -y install nodejs

COPY . /var/client/

CMD ["npm", "run", "start:dev", "--prefix", "/var/client/"]

EXPOSE 3000
