FROM node:14

COPY ./frontend/package.json /app/package.json
COPY ./frontend/package-lock.json /app/package-lock.json
RUN npm i --prefix /app

CMD ["npm", "run", "dev", "--prefix", "/app"]

EXPOSE 3000
