### Finance category type #####################################################
GET http://localhost:3080/api/finance-category-type
Authorization: Bearer MY_TOKEN

###
GET http://localhost:3080/api/finance-category-type?ids=1
Authorization: Bearer MY_TOKEN

###
GET http://localhost:3080/api/finance-category-type/3
Authorization: Bearer MY_TOKEN

###
POST http://localhost:3080/api/finance-category-type
Authorization: Bearer MY_TOKEN
Content-Type: application/json

{
	"name": "My category type name"
}

###
PATCH http://localhost:3080/api/finance-category-type/5
Authorization: Bearer MY_TOKEN
Content-Type: application/json

{
	"name": "My UPDATED category type name"
}

###
DELETE http://localhost:3080/api/finance-category-type/7
Authorization: Bearer MY_TOKEN



### Finance category ##########################################################
GET http://localhost:3080/api/finance-category
Authorization: Bearer MY_TOKEN

###
GET http://localhost:3080/api/finance-category/10
Authorization: Bearer MY_TOKEN

###
POST http://localhost:3080/api/finance-category
Authorization: Bearer MY_TOKEN
Content-Type: application/json

{
	"name": "My category name",
	"typeId": 2
}

###
PATCH http://localhost:3080/api/finance-category/16
Authorization: Bearer MY_TOKEN
Content-Type: application/json

{
	"name": "My UPDATED category name",
	"typeId": 1
}

###
DELETE http://localhost:3080/api/finance-category/18
Authorization: Bearer MY_TOKEN



### Finance record ############################################################
GET http://localhost:3080/api/finance-record?take=4&skip=200
Authorization: Bearer MY_TOKEN

###
GET http://localhost:3080/api/finance-record/250
Authorization: Bearer MY_TOKEN

###
POST http://localhost:3080/api/finance-record
Authorization: Bearer MY_TOKEN
Content-Type: application/json

{
	"amount": 5432,
	"categoryId": 3,
	"date": "2021-10-02"
}

###
PATCH http://localhost:3080/api/finance-record/330
Authorization: Bearer MY_TOKEN
Content-Type: application/json

{
	"amount": 2345,
	"categoryId": 4,
	"date": "2021-10-01",
	"isTrashed": true
}

###
DELETE http://localhost:3080/api/finance-record/331
Authorization: Bearer MY_TOKEN



### User ######################################################################
GET http://localhost:3080/api/user
Authorization: Bearer MY_TOKEN

###
GET http://localhost:3080/api/user/me
Authorization: Bearer MY_TOKEN

###
GET http://localhost:3080/api/user?id=3&username=sasha
Authorization: Bearer MY_TOKEN

###
POST http://localhost:3080/api/user
Content-Type: application/json

{
	"username": "johndoe",
	"password": "pass123"
}

###
PATCH http://localhost:3080/api/user/5
Authorization: Bearer MY_TOKEN
Content-Type: application/json

{
	"username": "johndoe",
	"password": "pass123"
}

###
DELETE http://localhost:3080/api/user/2
Authorization: Bearer MY_TOKEN



### Auth ######################################################################
POST http://localhost:3080/api/login
Content-Type: application/json

{
	"username": "username",
	"password": "password"
}
