FROM node:14

COPY ./backend/package.json /app/package.json
COPY ./backend/package-lock.json /app/package-lock.json

RUN npm i --prefix /app

CMD ["npm", "run", "dev", "--prefix", "/app"]

EXPOSE 3080
