### Finance category type
GET http://localhost:3080/api/finance-category-type
Authorization: 'Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJzYXNoYSIsImlhdCI6MTYzMzI5MDk0NiwiZXhwIjoxNjM0MTU0OTQ2fQ.oiLvsMWzE-YK0sbDRPcdRll3Iv3B7k-eeiUUxcqfAfGXyoliuKdR1k4mRNC6in2J'

###
GET http://localhost:3080/api/finance-category-type?ids=1,2

###
GET http://localhost:3080/api/finance-category-type?ids=2

###
POST http://localhost:3080/api/finance-category-type/ HTTP/1.1
Content-Type: application/json

{
	"name": "My category type name"
}

###
PATCH http://localhost:3080/api/finance-category-type/5 HTTP/1.1
Content-Type: application/json

{
	"name": "My UPDATED category type name"
}

###
DELETE http://localhost:3080/api/finance-category-type/6 HTTP/1.1



### Finance category ##########################################################
GET http://localhost:3080/api/finance-category

###
GET http://localhost:3080/api/finance-category/17

###
POST http://localhost:3080/api/finance-category/ HTTP/1.1
Content-Type: application/json

{
	"name": "My category name",
	"typeId": 2
}

###
PATCH http://localhost:3080/api/finance-category/16 HTTP/1.1
Content-Type: application/json

{
	"name": "My UPDATED category name",
	"typeId": 1
}

###
DELETE http://localhost:3080/api/finance-category/17 HTTP/1.1



### Finance record ############################################################
GET http://localhost:3080/api/finance-record

###
GET http://localhost:3080/api/finance-record/250

###
POST http://localhost:3080/api/finance-record/ HTTP/1.1
Content-Type: application/json

{
	"amount": 5432,
	"categoryId": 3,
	"date": "2021-10-02"
}

###
PATCH http://localhost:3080/api/finance-record/330 HTTP/1.1
Content-Type: application/json

{
	"amount": 2345,
	"categoryId": 4,
	"date": "2021-10-01",
	"isTrashed": true
}

###
DELETE http://localhost:3080/api/finance-record/331 HTTP/1.1



### User ######################################################################
GET http://localhost:3080/api/user

###
GET http://localhost:3080/api/user?id=3&username=sasha

###
POST http://localhost:3080/api/user/ HTTP/1.1
Content-Type: application/json

{
	"username": "slava",
	"password": "slava228"
}

###
PATCH http://localhost:3080/api/user/5 HTTP/1.1
Content-Type: application/json

{
	"username": "slava1",
	"password": "slava228"
}

###
DELETE http://localhost:3080/api/user/5 HTTP/1.1



### Auth ######################################################################
POST http://localhost:3080/api/login/ HTTP/1.1
Content-Type: application/json

{
	"username": "my_username",
	"password": "my_password"
}
