FROM postgres:14.4

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl jq lzop

RUN mkdir /var/app/dumps -p

COPY ./download-and-init-databases.sh /var/app/download-and-init-databases.sh
COPY ./truncate-all-tables.sh /var/app/truncate-all-tables.sh

EXPOSE 5432
