FROM postgres:14.4

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl jq lzop

RUN mkdir /var/app/dumps -p

COPY ./download-and-init-dev-db.sh /var/app/download-and-init-dev-db.sh

EXPOSE 5432
