FROM postgres:13.3

ARG REMOTE_API_KEY
ARG REMOTE_DB_NAME
ENV REMOTE_API_KEY=$REMOTE_API_KEY
ENV REMOTE_DB_NAME=$REMOTE_DB_NAME

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y curl jq lzop

RUN mkdir /app
RUN mkdir /app/dumps

COPY ./db/init.sh /app

RUN bash /app/init.sh

EXPOSE 5432
